"""empty message

Revision ID: 2d05986e3443
Revises: 145e5c829701
Create Date: 2021-04-27 12:16:57.214532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d05986e3443'
down_revision = '145e5c829701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Document', sa.Column('wc', sa.Integer(), nullable=True), schema='personality')
    op.add_column('Document', sa.Column('wc', sa.Integer(), nullable=True), schema='twitter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Document', 'wc', schema='twitter')
    op.drop_column('Document', 'wc', schema='personality')
    # ### end Alembic commands ###
