"""empty message

Revision ID: 43d400746613
Revises: 02b0f62a7af1
Create Date: 2021-03-16 21:27:10.494563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43d400746613'
down_revision = '02b0f62a7af1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('features', sa.ARRAY(sa.Float()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('o', sa.Float(), nullable=True),
    sa.Column('c', sa.Float(), nullable=True),
    sa.Column('e', sa.Float(), nullable=True),
    sa.Column('a', sa.Float(), nullable=True),
    sa.Column('n', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    op.drop_table('Document')
    # ### end Alembic commands ###
