"""empty message

Revision ID: 94b9054df41d
Revises: 27d22edc9b3b
Create Date: 2021-03-08 18:12:16.744279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94b9054df41d'
down_revision = '27d22edc9b3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Documents', sa.Column('text', sa.Text(), nullable=True))
    op.drop_column('Documents', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Documents', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('Documents', 'text')
    # ### end Alembic commands ###
