"""empty message

Revision ID: caa3a29a5243
Revises: 
Create Date: 2021-03-23 14:15:37.986183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caa3a29a5243'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('features', sa.ARRAY(sa.Float()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='personality'
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('o', sa.Float(), nullable=True),
    sa.Column('c', sa.Float(), nullable=True),
    sa.Column('e', sa.Float(), nullable=True),
    sa.Column('a', sa.Float(), nullable=True),
    sa.Column('n', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='personality'
    )
    op.create_table('Document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('features', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('stored_tweets', sa.Integer(), nullable=True),
    sa.Column('first', sa.Numeric(), nullable=True),
    sa.Column('last', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='twitter'
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follows', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='twitter'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User', schema='twitter')
    op.drop_table('Document', schema='twitter')
    op.drop_table('User', schema='personality')
    op.drop_table('Document', schema='personality')
    # ### end Alembic commands ###
