"""empty message

Revision ID: d3b5a01ecf32
Revises: 
Create Date: 2021-03-10 16:19:23.810195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3b5a01ecf32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('o', sa.Float(), nullable=True),
    sa.Column('c', sa.Float(), nullable=True),
    sa.Column('e', sa.Float(), nullable=True),
    sa.Column('a', sa.Float(), nullable=True),
    sa.Column('n', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    op.drop_table('Documents')
    # ### end Alembic commands ###
