"""empty message

Revision ID: efd82e3aa3f9
Revises: a0b1016579db
Create Date: 2021-03-21 00:42:01.770958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efd82e3aa3f9'
down_revision = 'a0b1016579db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('total', sa.Integer(), nullable=True), schema='twitter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'total', schema='twitter')
    # ### end Alembic commands ###
